[package]
name = "pctrl"
version = "0.1.0"
edition = "2021"

[dependencies]
pulsectl-rs = "0.3.2"
log = "0.4.14"
env_logger = "0.10.0"
anyhow = "1.0.44"
clap = { version="4.5.2", features=["derive"] }
